2020-11-04 12:19:52,430 INFO: Microblog startup [in /home/mayank1729/microblog/app/__init__.py:40]
2020-11-04 18:24:35,969 INFO: Microblog startup [in /home/mayank1729/microblog/app/__init__.py:40]
2020-11-04 18:27:16,660 INFO: Microblog startup [in /home/mayank1729/microblog/app/__init__.py:40]
2020-11-04 18:27:53,059 INFO: Microblog startup [in /home/mayank1729/microblog/app/__init__.py:40]
2020-11-04 18:28:29,475 INFO: Microblog startup [in /home/mayank1729/microblog/app/__init__.py:40]
2020-11-04 18:28:46,049 INFO: Microblog startup [in /home/mayank1729/microblog/app/__init__.py:40]
2020-11-04 20:22:00,356 INFO: Microblog startup [in /home/mayank1729/microblog/app/__init__.py:40]
2020-11-04 20:26:35,396 INFO: Microblog startup [in /home/mayank1729/microblog/app/__init__.py:40]
2020-11-04 20:26:51,229 INFO: Microblog startup [in /home/mayank1729/microblog/app/__init__.py:40]
2020-11-04 20:28:35,232 INFO: Microblog startup [in /home/mayank1729/microblog/app/__init__.py:40]
2020-11-04 20:34:00,465 INFO: Microblog startup [in /home/mayank1729/microblog/app/__init__.py:40]
2020-11-04 20:37:48,723 INFO: Microblog startup [in /home/mayank1729/microblog/app/__init__.py:40]
2020-11-04 20:42:41,115 INFO: Microblog startup [in /home/mayank1729/microblog/app/__init__.py:40]
2020-11-04 21:33:52,515 INFO: Microblog startup [in /home/mayank1729/microblog/app/__init__.py:40]
2020-11-04 21:34:32,197 INFO: Microblog startup [in /home/mayank1729/microblog/app/__init__.py:40]
2020-11-05 13:58:35,357 INFO: Microblog startup [in /home/mayank1729/microblog/app/__init__.py:40]
2020-11-05 14:00:36,682 INFO: Microblog startup [in /home/mayank1729/microblog/app/__init__.py:40]
2020-11-05 14:00:42,989 ERROR: Exception on / [GET] [in /home/mayank1729/microblog/venv/lib/python3.8/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/mayank1729/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/mayank1729/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/mayank1729/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/mayank1729/microblog/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/mayank1729/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/mayank1729/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/mayank1729/microblog/venv/lib/python3.8/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/mayank1729/microblog/app/routes.py", line 30, in index
    posts = current_user.followed_post().all
  File "/home/mayank1729/microblog/venv/lib/python3.8/site-packages/werkzeug/local.py", line 347, in __getattr__
    return getattr(self._get_current_object(), name)
AttributeError: 'User' object has no attribute 'followed_post'
2020-11-05 14:03:07,503 INFO: Microblog startup [in /home/mayank1729/microblog/app/__init__.py:40]
2020-11-05 14:03:12,545 ERROR: Exception on / [GET] [in /home/mayank1729/microblog/venv/lib/python3.8/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/mayank1729/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/mayank1729/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/mayank1729/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/mayank1729/microblog/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/mayank1729/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/mayank1729/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/mayank1729/microblog/venv/lib/python3.8/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/mayank1729/microblog/app/routes.py", line 31, in index
    return render_template('index.html',title='Home Page', posts=posts, form=form)
  File "/home/mayank1729/microblog/venv/lib/python3.8/site-packages/flask/templating.py", line 138, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/home/mayank1729/microblog/venv/lib/python3.8/site-packages/jinja2/environment.py", line 930, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/home/mayank1729/microblog/venv/lib/python3.8/site-packages/jinja2/environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/home/mayank1729/microblog/venv/lib/python3.8/site-packages/jinja2/environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "/home/mayank1729/microblog/venv/lib/python3.8/site-packages/jinja2/loaders.py", line 127, in load
    code = environment.compile(source, name, filename)
  File "/home/mayank1729/microblog/venv/lib/python3.8/site-packages/jinja2/environment.py", line 638, in compile
    self.handle_exception(source=source_hint)
  File "/home/mayank1729/microblog/venv/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/mayank1729/microblog/venv/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/mayank1729/microblog/app/templates/index.html", line 10, in template
    {{ form.post(cols=32, rows=4 }}<br>
jinja2.exceptions.TemplateSyntaxError: unexpected '}', expected ')'
2020-11-05 14:03:15,684 ERROR: Exception on / [GET] [in /home/mayank1729/microblog/venv/lib/python3.8/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/mayank1729/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/mayank1729/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/mayank1729/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/mayank1729/microblog/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/mayank1729/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/mayank1729/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/mayank1729/microblog/venv/lib/python3.8/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/mayank1729/microblog/app/routes.py", line 31, in index
    return render_template('index.html',title='Home Page', posts=posts, form=form)
  File "/home/mayank1729/microblog/venv/lib/python3.8/site-packages/flask/templating.py", line 138, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/home/mayank1729/microblog/venv/lib/python3.8/site-packages/jinja2/environment.py", line 930, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/home/mayank1729/microblog/venv/lib/python3.8/site-packages/jinja2/environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/home/mayank1729/microblog/venv/lib/python3.8/site-packages/jinja2/environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "/home/mayank1729/microblog/venv/lib/python3.8/site-packages/jinja2/loaders.py", line 127, in load
    code = environment.compile(source, name, filename)
  File "/home/mayank1729/microblog/venv/lib/python3.8/site-packages/jinja2/environment.py", line 638, in compile
    self.handle_exception(source=source_hint)
  File "/home/mayank1729/microblog/venv/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/mayank1729/microblog/venv/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/mayank1729/microblog/app/templates/index.html", line 10, in template
    {{ form.post(cols=32, rows=4 }}<br>
jinja2.exceptions.TemplateSyntaxError: unexpected '}', expected ')'
2020-11-05 14:04:00,755 INFO: Microblog startup [in /home/mayank1729/microblog/app/__init__.py:40]
2020-11-05 14:06:55,407 INFO: Microblog startup [in /home/mayank1729/microblog/app/__init__.py:40]
2020-11-05 14:27:33,841 INFO: Microblog startup [in /home/mayank1729/microblog/app/__init__.py:40]
2020-11-05 14:51:26,117 INFO: Microblog startup [in /home/mayank1729/microblog/app/__init__.py:40]
